{% set version = '4023.85' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fassets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fAssets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fAssets/fAssets_{{ version }}.tar.gz
  sha256: 2d02fcc49fe7bac673fe4b3833e4f9e604c42cef6608e36abba57a845d1d3afb

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-ecodist
    - r-energy
    - r-fbasics
    - r-fmultivar
    - r-mvnormtest
    - r-robustbase
    - r-sn
    - r-timedate
    - r-timeseries
  run:
    - r-base
    - r-mass
    - r-ecodist
    - r-energy
    - r-fbasics
    - r-fmultivar
    - r-mvnormtest
    - r-robustbase
    - r-sn
    - r-timedate
    - r-timeseries

test:
  commands:
    - $R -e "library('fAssets')"           # [not win]
    - "\"%R%\" -e \"library('fAssets')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/rmetrics/
  license: GPL-2.0-or-later
  summary: A collection of functions to manage, to investigate and to analyze data sets of financial
    assets from different points of view.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - janjagusch


# Package: fAssets
# Title: Rmetrics - Analysing and Modelling Financial Assets
# Date: 2023-04-20
# Version: 4023.85
# Authors@R: c( person("Diethelm", "Wuertz", role = "aut"), person("Tobias", "Setz", role = "aut"), person("Yohan", "Chalabi", role = "aut"), person("Stefan", "Theussl", role = c("aut", "cre"), email = "Stefan.Theussl@R-project.org", comment = c(ORCID = "0000-0002-6523-4620")) )
# Description: A collection of functions to manage, to investigate and to analyze data sets of financial assets from different points of view.
# Depends: R (>= 2.15.1), timeDate, timeSeries, fBasics
# Imports: fMultivar, robustbase, MASS, sn, ecodist, mvnormtest, energy, grDevices, graphics, stats
# Suggests: methods, mnormt, RUnit
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/rmetrics/
# NeedsCompilation: no
# Packaged: 2023-04-21 19:38:00 UTC; parallels
# Author: Diethelm Wuertz [aut], Tobias Setz [aut], Yohan Chalabi [aut], Stefan Theussl [aut, cre] (<https://orcid.org/0000-0002-6523-4620>)
# Maintainer: Stefan Theussl <Stefan.Theussl@R-project.org>
# Repository: CRAN
# Date/Publication: 2023-04-24 14:00:02 UTC
